{ vars, ... }:
let
  inherit (vars) browser terminal editor;
in
{
  wayland.windowManager.hyprland.settings = {
    bind = [
      "SUPER,Return,exec,${terminal}"
      "SUPER,SPACE,exec,rofi-launcher"
      "SUPER ALT,W,exec,wallsetter"
      "SUPER SHIFT,N,exec,swaync-client -rs"
      "SUPER SHIFT,R,exec,sh -c 'pkill waybar && hyprctl dispatch exec waybar'"
      "SUPER,W,exec,${browser}"
      "SUPER SHIFT,W,exec,sh -c '${browser} --private-window || ${browser} --incognito'"
      "SUPER,E,exec,${editor}"
      "SUPER,Y,exec,kitty -e yazi"
      "SUPER,S,exec,screenshootin"
      "SUPER CTRL,S,exec,hyprshot -m output -o $HOME/Pictures/ScreenShots"
      "SUPER SHIFT,S,exec,hyprshot -m window -o $HOME/Pictures/ScreenShots"
      "SUPER ALT,S,exec,hyprshot -m region -o $HOME/Pictures/ScreenShots"
      "SUPER,D,exec,vesktop"
      "SUPER SHIFT,M,exec,vesktop-mute"
      "SUPER SHIFT,D,exec,vesktop-deafen"
      "SUPER,O,togglespecialworkspace,obs"
      "SUPER,M,togglespecialworkspace,spotify"
      "SUPER,N,togglespecialworkspace,config"
      "SUPER,C,exec,hyprpicker -a"
      "SUPER,G,togglespecialworkspace,gamestore"
      "SUPER,T,exec, thunar"
      "SUPER,A,exec,pavucontrol"
      "SUPER,Q,killactive,"
      "SUPER,P,pseudo,"
      "SUPER,V,exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
      "SUPER SHIFT,I,layoutmsg,togglesplit"
      "SUPER,F,fullscreen,"
      "SUPER SHIFT,F,togglefloating,"
      "SUPER ALT,F,workspaceopt, allfloat"
      "SUPER SHIFT,C,exit,"
      "SUPER SHIFT,left,movewindow,l"
      "SUPER SHIFT,right,movewindow,r"
      "SUPER SHIFT,up,movewindow,u"
      "SUPER SHIFT,down,movewindow,d"
      "SUPER SHIFT,h,movewindow,l"
      "SUPER SHIFT,l,movewindow,r"
      "SUPER SHIFT,k,movewindow,u"
      "SUPER SHIFT,j,movewindow,d"
      "SUPER ALT, left, swapwindow,l"
      "SUPER ALT, right, swapwindow,r"
      "SUPER ALT, up, swapwindow,u"
      "SUPER ALT, down, swapwindow,d"
      "SUPER ALT, 43, swapwindow,l"
      "SUPER ALT, 46, swapwindow,r"
      "SUPER ALT, 45, swapwindow,u"
      "SUPER ALT, 44, swapwindow,d"
      "SUPER,left,resizeactive,-60 0"
      "SUPER,right,resizeactive,60 0"
      "SUPER,up,resizeactive,0 -60"
      "SUPER,down,resizeactive,0 60"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPER,1,workspace,1"
      "SUPER,2,workspace,2"
      "SUPER,3,workspace,3"
      "SUPER,4,workspace,4"
      "SUPER,5,workspace,5"
      "SUPER,6,workspace,6"
      "SUPER,7,workspace,7"
      "SUPER,8,workspace,8"
      "SUPER,9,workspace,9"
      "SUPER,0,workspace,10"
      "SUPER SHIFT,1,movetoworkspace,1"
      "SUPER SHIFT,2,movetoworkspace,2"
      "SUPER SHIFT,3,movetoworkspace,3"
      "SUPER SHIFT,4,movetoworkspace,4"
      "SUPER SHIFT,5,movetoworkspace,5"
      "SUPER SHIFT,6,movetoworkspace,6"
      "SUPER SHIFT,7,movetoworkspace,7"
      "SUPER SHIFT,8,movetoworkspace,8"
      "SUPER SHIFT,9,movetoworkspace,9"
      "SUPER SHIFT,0,movetoworkspace,10"
      "SUPER CONTROL,right,workspace,e+1"
      "SUPER CONTROL,left,workspace,e-1"
      "SUPER,mouse_down,workspace, e+1"
      "SUPER,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,playerctl --player=spotify volume 0.05+"
      ",XF86AudioLowerVolume,exec,playerctl --player=spotify volume 0.05-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl --player=spotify,firefox play-pause"
      ",XF86AudioPause, exec, playerctl --player=spotify,firefox play-pause"
      ",XF86AudioNext, exec, playerctl --player=spotify,firefox next"
      ",XF86AudioPrev, exec, playerctl --player=spotify,firefox previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "SUPER, mouse:272, movewindow"
      "SUPER, mouse:273, resizewindow"
    ];

    # Special workspaces autostart
    workspace = [
      "special:config, on-created-empty: ${editor} ~/nix-config"
      "special:obs, on-created-empty: obs"
      "special:spotify, on-created-empty: spotify"
      "special:gamestore, on-created-empty: steam"

      # Smart gaps
      "w[tv1], gapsout:0, gapsin:0"
      "f[1], gapsout:0, gapsin:0"
    ];
  };
}
