{ ... }:
{
  wayland.windowManager.hyprland = {
    settings = {
      windowrule = [
        #"no_blur true, match:xwayland true" # Helps prevent odd borders/shadows for xwayland apps
        # downside it can impact other xwayland apps
        # This rule is a template for a more targeted approach
        "no_blur true, match:class ^(\bresolve\b)$, match:xwayland true" # Window rule for just resolve
        "tag +file-manager, match:class ^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$"
        "tag +terminal, match:class ^(com.mitchellh.ghostty|org.wezfurlong.wezterm|Alacritty|kitty|kitty-dropterm)$"
        "tag +browser, match:class ^(Brave-browser(-beta|-dev|-unstable)?)$"
        "tag +browser, match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$"
        "tag +browser, match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$"
        "tag +browser, match:class ^([Tt]horium-browser|[Cc]achy-browser)$"
        "tag +projects, match:class ^(codium|codium-url-handler|VSCodium)$"
        "tag +projects, match:class ^(VSCode|code-url-handler)$"
        "tag +im, match:class ^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$"
        "tag +im, match:class ^([Ff]erdium)$"
        "tag +im, match:class ^([Ww]hatsapp-for-linux)$"
        "tag +im, match:class ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$"
        "tag +im, match:class ^(teams-for-linux)$"
        "tag +games, match:class ^(gamescope)$"
        "tag +games, match:class ^(steam_app_\d+)$"
        "tag +gamestore, match:class ^([Ss]team)$"
        "tag +gamestore, match:title ^([Ll]utris)$"
        "tag +gamestore, match:class ^(com.heroicgameslauncher.hgl)$"
        "tag +settings, match:class ^(gnome-disks|wihotspot(-gui)?)$"
        "tag +settings, match:class ^([Rr]ofi)$"
        "tag +settings, match:class ^(file-roller|org.gnome.FileRoller)$"
        "tag +settings, match:class ^(nm-applet|nm-connection-editor|blueman-manager)$"
        "tag +settings, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
        "tag +settings, match:class ^(nwg-look|qt5ct|qt6ct|[Yy]ad)$"
        "tag +settings, match:class (xdg-desktop-portal-gtk)"
        "tag +settings, match:class (.blueman-manager-wrapped)"
        "tag +settings, match:class (nwg-displays)"
        "workspace special:gamestore, match:class ^([Ss]team)$"
        "move 72% 7%, match:title ^(Picture-in-Picture)$"
        "center true, match:class ^([Ff]erdium)$"
        "float true, match:class ^([Ww]aypaper)$"
        "center true, match:class ^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$"
        "center true, match:title ^(Authentication Required)$"
        "idle_inhibit fullscreen, match:class ^(*)$"
        "idle_inhibit fullscreen, match:title ^(*)$"
        "idle_inhibit fullscreen, match:fullscreen true"
        "float true, match:tag settings*"
        "float true, match:class ^([Ff]erdium)$"
        "float true, match:title ^(Picture-in-Picture)$"
        "float true, match:class ^(mpv|com.github.rafostar.Clapper)$"
        "float true, match:title ^(Authentication Required)$"
        "float true, match:class (codium|codium-url-handler|VSCodium), match:title negative:(.*codium.*|.*VSCodium.*)"
        "float true, match:class ^(com.heroicgameslauncher.hgl)$, match:title negative:(Heroic Games Launcher)"
        "float true, match:class ^([Ss]team)$, match:title negative:^([Ss]team)$"
        "float true, match:initial_title (Add Folder to Workspace)"
        "float true, match:initial_title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "float true, match:title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "center true, match:initial_title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "center true, match:title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "float true, match:initial_title (wants to save)"
        "size 70% 60%, match:initial_title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "size 70% 60%, match:title ^([Oo]pen|[Ss]ave|[Ss]elect|[Cc]hoose).*(file|files|folder|folders|File|Files|Folder|Folders).*$"
        "size 70% 60%, match:initial_title (Add Folder to Workspace)"
        "size 70% 70%, match:tag settings*"
        "size 60% 70%, match:class ^([Ff]erdium)$"
        "opacity 1.0 1.0, match:tag browser*"
        "opacity 0.9 0.8, match:tag projects*"
        "opacity 1.0 1.0, match:tag im*"
        "opacity 0.9 0.8, match:tag file-manager*"
        "opacity 1.0 0.9, match:tag terminal*"
        "opacity 0.8 0.7, match:tag settings*"
        "opacity 0.8 0.7, match:class ^(gedit|org.gnome.TextEditor|mousepad)$"
        "opacity 0.9 0.8, match:class ^(seahorse)$ # gnome-keyring gui"
        "opacity 1.0 1.0, match:title ^(Picture-in-Picture)$"
        "pin true, match:class ^([Ss]team)$, match:title negative:^(Steam|Friends List)$"
        "pin true, match:title ^(Picture-in-Picture)$"
        "keep_aspect_ratio true, match:title ^(Picture-in-Picture)$"
        "no_blur true, match:tag games*"
        "fullscreen true, match:tag games*"

        # Smart gaps
        "border_size 0, match:float false, match:workspace w[t1]"
        "rounding 0, match:float false, match:workspace w[t1]"
        "border_size 0, match:float false, match:workspace w[tg1]"
        "rounding 0, match:float false, match:workspace w[tg1]"
        "border_size 0, match:float false, match:workspace f[1]"
        "rounding 0, match:float false, match:workspace f[1]"
      ];
    };
  };
}
