{ ... }:
{
  imports = [
    ./bat.nix
    ./btop.nix
    ./bottom.nix
    ./cava.nix
    ./cursor.nix
    ./dotfiles.nix
    ./eza.nix
    ./fastfetch
    ./fzf.nix
    ./gh.nix
    ./git.nix
    ./gtk.nix
    ./htop.nix
    ./hyprland.nix
    ./lazygit.nix
    ./obs-studio.nix
    ./qt.nix
    ./scripts
    ./starship.nix
    ./stylix.nix
    ./swappy.nix
    ./swaync.nix
    ./tealdeer.nix
    ./xdg.nix
    ./zoxide.nix
  ];
}
